### ISSUE TITLE
Ридми не очень

### ISSUE THREAD

**Issue by rptl8sr** [Leo-MathGuy/yandexGolangMod1#1]
1) Такой командой будет сложно запустить `go run cmd/calcapi.go` проект

```
tree
.
├── LICENCE.md
├── README.md
├── README.ru.md
├── cmd
│   └── main.go
```

2) Нет примеров использования запросов

**Comment by Leo-MathGuy** [comment]
1. Блин забыл обновить Английский ридми сорри

2. Не совсем понимаю, тесты проверяют 50 раз в те кто проверяют уже должны знать, но сделаю

**Comment by Leo-MathGuy** [comment]
Вделано

**Comment by rptl8sr** [comment]
1. Ага, появилось )

2. Формально есть такое. условие. То, что все одинаково проверяют — не показатель же, это сот сейчас такая ситуация, что у всех проект одинаковый. Примеры использования АПИ просто мастхев, бестпрактис и хороший тон. 
Тесты даже если покрывают полностью всю прогу — не гарантируют, что АПИшка будет работать.

Так что что-то в духе
`curl -L -X POST 'http://localhost:8080/api/v1/calculate' -H 'Content-Type: application/json' -d '{"expression":"12/0"}'`
очень неплохо иметь в документации

**Comment by Leo-MathGuy** [comment]
Добавил)
